# Generated by Django 4.2 on 2023-04-14 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participants', models.ManyToManyField(blank=True, related_name='chats', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='texto')),
                ('terms', models.JSONField(blank=True, null=True, verbose_name='termos')),
                ('video_paths', models.JSONField(blank=True, null=True, verbose_name='caminho de vídeos')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_to', to='chat.chat', verbose_name='para')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='accounts.account', verbose_name='criado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to='accounts.account', verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
