# Generated by Django 4.2 on 2023-05-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_participants_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatparticipant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to='chat.chat'),
        ),
    ]
